// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzt8qxuymCUb1M0SU5YQf-x8dpSNlytCw',
    appId: '1:784449543659:web:a6d74c8462736a14b0cdae',
    messagingSenderId: '784449543659',
    projectId: 'flutter-app-4c5e7',
    authDomain: 'flutter-app-4c5e7.firebaseapp.com',
    storageBucket: 'flutter-app-4c5e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCdPC74x2W_JKvTc-KwnWy-Lu_-xVm7U',
    appId: '1:784449543659:android:e1807063ea5be764b0cdae',
    messagingSenderId: '784449543659',
    projectId: 'flutter-app-4c5e7',
    storageBucket: 'flutter-app-4c5e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiCoyvag_yepWZiPjxNCNOIjglS8HCkQY',
    appId: '1:784449543659:ios:cb4777c3be1df966b0cdae',
    messagingSenderId: '784449543659',
    projectId: 'flutter-app-4c5e7',
    storageBucket: 'flutter-app-4c5e7.appspot.com',
    androidClientId: '784449543659-i2bi7kecokllhd462g8csrohu8k2bhkc.apps.googleusercontent.com',
    iosClientId: '784449543659-qtgpontrmiggtkug6r9m0km7cdtpg1gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiCoyvag_yepWZiPjxNCNOIjglS8HCkQY',
    appId: '1:784449543659:ios:cb4777c3be1df966b0cdae',
    messagingSenderId: '784449543659',
    projectId: 'flutter-app-4c5e7',
    storageBucket: 'flutter-app-4c5e7.appspot.com',
    androidClientId: '784449543659-i2bi7kecokllhd462g8csrohu8k2bhkc.apps.googleusercontent.com',
    iosClientId: '784449543659-qtgpontrmiggtkug6r9m0km7cdtpg1gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
